version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
      - 8081:8081

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://api:8080
    # Add any additional configurations for your frontend service

  api:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80